title: RmmbrIt Docs
description: RmmbrIt - your memory's backup drive.
theme: just-the-docs

url: https://wtmadaj.github.io/rmmbrit-docs

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

search:
    button: true

#callouts:
#  note:
#    title: Note
#  warning:
#    title: Warning
#    color: red
#  danger:
#    title: Danger
#  tip:
#    title: Tip
#  info:
#    title: Info